version: '3.8'

# 👍 Usou Docker / Compose
services:
  frontend:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: frontend
    volumes:
      - './:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start